server:
  port: 5656

security:
  basic:
    enabled: false
  oauth2:
    resource:
      user-info-uri: http://api-gateway:7979/uaa/current
      id: ${spring.application.name:}
    client:
      clientId: server
      clientSecret: server
      accessTokenUri: http://api-gateway:7979/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  profiles:
    active: @profileActive@
  rabbitmq:
    host: mbox-rabbitmq
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1
  redis:
    host: mbox-redis
    port: 6379
    password: qianhezi9876
    database: 0
    timeout: 0
    pool:
      max-active: 100
      max-wait: 1
      max-idle: 50
      min-idle: 0
  datasource:
    url: jdbc:mysql://mbox-db-mysql:3306/devmbox_java?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: qianhezi@2015test
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    db-name: devmbox_java

comb:
  swagger2:
    enable: true
    base-package: com.qhz.comb
    title : Comb
    description: Comb Restful API docs
    version: 1.0
    apiName: Authorization
    apiKeyName: Authorization

logging:
  file: ../logs/${spring.application.name}.log
