server:
  port: 9000

spring:
    datasource:
      url: jdbc:mysql://mbox-db-mysql:3306/devmbox_java?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: qianhezi@2015test
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      db-name: devmbox_java
comb:
  devtools: #开发工具
    project-location: D:/
    developer: jiangting
    table-prefix: d_

security:
  basic:
    enabled: false
