server:
  port: 8031
  tomcat:
    uri-encoding: UTF-8
    remote-ip-header: x-forwarded-for
  use-forward-headers: true

#security:
#  basic:
#    enabled: false

spring:
  cache:
    cache-names: comb-provider-user-cache
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mbox-db-mysql:3306/devmbox_hx?characterEncoding=utf8&useSSL=false
    username: root
    password: qianhezi@2015test
    filters: stat,wall
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

